# Copyright (C) 2017 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/grandneove3g/setup-makefiles.sh

PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/bin/engpc:system/bin/engpc
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libatparser.so:system/lib/libatparser.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/etc/gps.conf:system/etc/gps.conf
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/bin/gpsd:system/bin/gpsd
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/bin/gps.cer:system/bin/gps.cer
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libboost.so:system/lib/libboost.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/etc/audio_hw.xml:system/etc/audio_hw.xml
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/etc/audio_para:system/etc/audio_para
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/etc/codec_pga.xml:system/etc/codec_pga.xml
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/etc/tiny_hw.xml:system/etc/tiny_hw.xml
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libatchannel.so:system/lib/libatchannel.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/etc/wifi/bcmdhd_apsta.bin:system/vendor/etc/wifi/bcmdhd_apsta.bin
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/etc/wifi/bcmdhd_mfg.bin:system/vendor/etc/wifi/bcmdhd_mfg.bin
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/etc/wifi/bcmdhd_sta.bin:system/vendor/etc/wifi/bcmdhd_sta.bin
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/etc/wifi/nvram_mfg.txt:system/vendor/etc/wifi/nvram_mfg.txt
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/vendor/firmware/BCM43430A1_001.002.009.0013.0018_ORC_GrandNeo_VE.hcd:system/vendor/firmware/BCM43430A1_001.002.009.0013.0018_ORC_GrandNeo_VE.hcd
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/bin/rild:system/bin/rild
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/bin/modemd:system/bin/modemd
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/bin/nvitemd:system/bin/nvitemd
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/bin/phoneserver:system/bin/phoneserver
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/bin/ext_data.sh:system/bin/ext_data.sh
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/bin/ext_symlink.sh:system/bin/ext_symlink.sh
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libril.so:system/lib/libril.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libisp.so:system/lib/libisp.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libion.so:system/lib/libion.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libion_sprd.so:system/lib/libion_sprd.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libomx_avcdec_hw_sprd.so:system/lib/libomx_avcdec_hw_sprd.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libomx_avcenc_hw_sprd.so:system/lib/libomx_avcenc_hw_sprd.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/lib/libomx_vpxdec_hw_sprd.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:system/lib/libomx_m4vh263dec_hw_sprd.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:system/lib/libomx_m4vh263enc_hw_sprd.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/hw/gralloc.sc8830.so:system/lib/hw/gralloc.sc8830.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/hw/lights.sc8830.so:system/lib/hw/lights.sc8830.so
PRODUCT_COPY_FILES +=   vendor/samsung/grandneove3g/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so
